### PR TITLE
[Dev] Fix dashboard build & deploy command

### PR DESCRIPTION
**Pull request by rlnsy**
## Changes
Allows the command
```
yarn deploy:dashboard:stage
```
to be run without error, by fixing problems in the project dependencies and lock files.

This is done through some lock-file magic, and requires updating Firebase modules the latest versions as well as fixing some minor conflicts with deeper dependencies.

## Requirements
Should remove all node_modules, re-run setup script, or use `yarn all`.

## PR Dependencies
N/A

## Merged Branches and Other Dependencies
N/A

## Testing
- [x] Manual - should be able to build and deploy dashboard using the command line

### CODE REVIEW

**Comment by rlnsy** [comment]
@SukiCai let me know if it works

**Comment by rlnsy** [comment]
Someone should test that mobile apps aren't broken.

**Review by MarkDavies0 — APPROVED** [review]

**Review by wynnset — APPROVED** [review]

**Comment by wynnset** [comment]
Is it normal that the lint mobile test is failing @rlnsy ?

**Comment by rlnsy** [comment]
> Is it normal that the lint mobile test is failing @rlnsy ?

@wynnset yeah it is. We forgot to remove or skip the test before merging in the new testing workflows, so this should be failing everywhere now.

**Pull request merged**
