### PR TITLE
Configs, dependencies and code edits to get Android and IOS google sign-in working

### PR DESCRIPTION
**Pull request by cara-wong**

### CODE REVIEW

**Comment by cara-wong** [comment]
This PR gets google sign-in working on both Android and IOS. 

For IOS also follow the steps [here](https://developers.google.com/identity/sign-in/ios/start-integrating) under "Add a URL scheme to your project"

**Comment by crugwiro** [comment]
Tested and confirmed that it works on my local.

**Comment by cara-wong** [comment]
Note: You must also set up the OAuth Consent Screen in the Google Console to get google sign-in working and enable the Google sign-in method in the firebase console. I've done this already for the bipolar-bridges project.

**Comment by cara-wong** [comment]
@wynnset ready for review/merge

**Review by crugwiro — APPROVED** [review]
Tested Locally. Bug fixed

**Review by wynnset — APPROVED** [review]

**Pull request merged**
