### PR TITLE
[Qol Survey] Improve qol survey saving implementation

### PR DESCRIPTION
**Pull request by MarkDavies0**
## Changes
adds `tiny-timer`
Submits the partial state of the Qol survey every 5 seconds instead of after each question. 

## Requirements

Requires: `yarn install` in /mobile

## Testing
Reset your user before going through the onboarding and completing the qol survey, check firebase as you go to confirm your survey is being saved every 5 seconds. 

- [x] Manual

### CODE REVIEW

**Comment by wynnset** [comment]
Getting this error:
image

**Comment by MarkDavies0** [comment]
@wynnset fixed

**Review by wynnset — APPROVED** [review]

**Comment by wynnset** [comment]
Looks great!

**Comment by wynnset** [comment]
Oh shoot @MarkDavies0 there are still errors popping up. This is on the latest version that's been released: image

We should make sure that `this.submissionTimer` is never set to null. I saw that in your code that was not the case always.

**Pull request merged**
