### PR TITLE
[QoL Survey] Extend data export to include all QoL related data

### PR DESCRIPTION
**Pull request by Mapleia**
## Changes
Added a function that listens for changes to the survey collection to export the latest data to the data-services. 

## Requirements
Requires[ qol-survey branch](https://github.com/bipolarbridges/data-services/tree/qol-survey) on data-services.
## PR Dependencies

Depends on: #28 
Depends on: #23 
Depends on: #73 

## Merged Branches and Other Dependencies
Merged branch(es):
#28 (merged)
#23 (merged)
#73 (merged)

## Testing
- [x] Automated

List of added tests:
- Jest 'Should export new survey data' in export.spec.ts

### CODE REVIEW

**Comment by rlnsy** [comment]
@Mapleia can you fix the merge conflicts with QoL-Survey?

**Comment by rlnsy** [comment]
Blocked since comparison is difficult due to multiple PR dependencies.

**Comment by rlnsy** [comment]
@Mapleia I've tried to fix this PR but things don't seem quite right (old version is on `qol-data-export-backup` branch). Do you mind taking a look at the failing stuff and seeing what went wrong or what might be missing.

**Comment by rlnsy** [comment]
@Mapleia I changed it back to the original branch a temporary base, but there are some problems and merge conflicts with both mock-backend and qol-survey

**Comment by rlnsy** [comment]
Failing with real backend now, might need to be updated.

**Comment by wynnset** [comment]
Obsolete

**Pull request closed without merging**
