### PR TITLE
Fix onboarding process

### PR DESCRIPTION
**Pull request by cara-wong**
- [x] Pull in changes from Maslo's new sign-in flow branch
- [x] Create new sendgrid template for the verification code + edit old template to align with new process
- [x] fix first email not sending upon invite from dashboard

- Set up configs in GCP [Didn't end of needing this]

### CODE REVIEW

**Comment by cara-wong** [comment]
**Steps to test:

** ** Already deployed functions and dashboard with the changes from this PR**

1. Add the changes from this PR to your working instance of the project
2. Invite a new user from the dashboard.
3. Build mobile, and from mobile click the link in the email that was sent to you (should open the app if it is installed)
4. Follow steps to onboard the user in mobile

Screenshots of what onboarding in the app should look like [here](https://www.notion.so/Maslo-mobile-screenshots-2ef2fe6ac5e0499fb4e74a8273fbbfa3)

**Review by crugwiro — APPROVED** [review]
Tested locally, everything works as expected.

**Review by rlnsy — APPROVED** [review]
@cara-wong It works great! My problem with sendgrid was that I hadn't actually acquired the verification code template id yet. Once I stuck that in everything was fine. LGTM

**Comment by cara-wong** [comment]
@wynnset moving this to "merge blocked" because rowan's environment setup PR should be merged first. Afterwards, the new template id configuration in this PR should be updated to match his convention

**Comment by wynnset** [comment]
@cara-wong can you change the base branch for this to rowan's branch and make the necessary updates now so that when his PR is merged in, we can merge this in right away?

**Comment by cara-wong** [comment]
@rlnsy as per Aidin's above request, can you take a quick look at my recent commits so this PR is ready to merge in after yours to align with the env setup process

**Review by rlnsy — APPROVED** [review]
@cara-wong I fixed the history so that this branch compares evenly against master. Since this is a standalone fix with a lot of file-changes, I'd rather merge it in then do all of the comparison against my environment variable system as one comparison to master. I might be wrong, but I don't see any dependency on that in this PR. Sound good?

**Comment by rlnsy** [comment]
Please note that I changed the base to reflect this. I did a quick scan to make sure that the only changes here are the one's associated with your fixes, but perhaps you can double-check.

**Comment by rlnsy** [comment]
Also to make sure everything is here, we should do a test deploy.

**Comment by rlnsy** [comment]
Tested ✅

**Comment by rlnsy** [comment]
@cara-wong Tagging you so you can post here when you have verified everything works on your end

**Comment by cara-wong** [comment]
thanks for testing this again @rlnsy also verified everything is working on my end.

**Comment by cara-wong** [comment]
@wynnset this PR now only relates to changes for the new onboarding feature. After it's merged first (before Rowan's env setup PR), Rowan will pull down the changes to his PR and add the additional variable that is added by this feature. I think this flow makes more sense - is this ok with you?

**Comment by wynnset** [comment]
@cara-wong yes that is fine with me, thanks! Is this ready to merge then?

**Comment by cara-wong** [comment]
@wynnset great - then yes this is ready to merge!

**Pull request merged**
