### PR TITLE
Configs/code to get android to build locally and sign in with email/password

### PR DESCRIPTION
**Pull request by cara-wong**
Added configs to install and use react-native unimodules, update settings for daemon process, manifest configs and using expo-camera

### CODE REVIEW

**Review by crugwiro — APPROVED** [review]

**Comment by wynnset** [comment]
@rlnsy will ensure this config is sufficient and review the code before marking it as ready for merge

**Comment by rlnsy** [comment]
@cara-wong @crugwiro And I concluded that my problems are likely just a consequence of not followed any setup yet (Android studio etc.) I feel like we could merge this if it works for both of you now. Alternatively, I can re-review once I've done my own setup using notion docs and the files here.

**Comment by cara-wong** [comment]
@rlnsy Sounds good, I think we are ok to merge this. To just get the app to build and run locally you only need to follow the android environment setup steps here (https://reactnative.dev/docs/environment-setup) and pull down the android dir from this branch. The steps on notion are for connecting the app to firebase so you can log in.

@wynnset This is ready to merge if you are ok with it.

**Comment by cara-wong** [comment]
@wynnset ready for review/merge

**Review by crugwiro — APPROVED** [review]
Tested locally. Bug fixed

**Review by wynnset — APPROVED** [review]

**Pull request merged**
