### PR TITLE
Upgrade firebase

### PR DESCRIPTION
**Pull request by rlnsy**
## Changes
Upgrades Firebase dependencies to a newer version, making changes in our code where necessary.

## Requirements
Requires: `yarn install` in the root and functions directories. May need to delete node modules to reset.

## PR Dependencies
Depends on: #27 (tests use to verify correctness)

## Merged Branches and Other Dependencies
Merged branch(es): None
Other dependencies: None

## Subtasks / Progress
N/A

## Preview
N/A

## Testing
Manual, Automated. 
- Test suites and build workflows from #27 verify code correctness.
- Mobile apps have been manually built and tested

### CODE REVIEW

**Comment by rlnsy** [comment]
@cara-wong @crugwiro Can you guys try running the mobile apps off of this branch when you get a chance? I'm not sure at this point whether or not there are any breaking changes. You'll probably want to use a fresh clone since the dependency versions are different - don't want them interfering with your main project.

**Comment by crugwiro** [comment]
@rlnsy Tested this on android/iOS the apps are building fine and login works.

**Comment by rlnsy** [comment]
@crugwiro Awesome good to know - and thanks!

**Comment by cara-wong** [comment]
@rlnsy Tested this branch with a fresh clone, android/ios builds and logins fine. I did see a couple weird things in the setup script:
1. Since the gsap version was updated in this PR, you now get this prompt to choose a gsap version during the setup script - not sure if we want this (@crugwiro also got this):
Screen Shot 2021-04-13 at 9 57 59 AM

2. I got this error during the setup script the first time I cloned and ran it. When I ran the script a second time I didn't get it - this might just be a local issue. (@crugwiro doesn't remember seeing it the first time he ran it, and he didn't see it when he ran it a second time either)
Screen Shot 2021-04-13 at 9 59 19 AM

**Comment by rlnsy** [comment]
@cara-wong @crugwiro both of those problems should be fixed now.

**Pull request closed without merging**
