### PR TITLE
[QoL History] [Life Domains] View current focus domains, strategies, and q.o.l. history

### PR DESCRIPTION
**Pull request by MarkDavies0**
### QoL History:
- add `aggregateScore` to `SurveyResults`
- add screens `qolHistoryMain`, `qolTimeline` and `QolHistoryStrategiesView`
- add `qolHistoryViewModel`
- scrollable graph (svg rendered!) to view entire score history
- rename `ChooseDomainsViewModel` and `ChooseStrategiesViewModel` to `DomainsViewModel` and `StrategiesViewModel` respectfully
- adds `react-native-paper` to render views above the orb
- add back button to qol survey
- `QolSurveyResults` - store an array of scores for each domain (1 numebr per question)
- match persona arm schema to `QolSurveyResults`
- a whole lot of refactoring

### Domains & Stratgies:
- Adds new screens: YourFocusDomainsView, PastStrategiesVIew, viewDomainsView and accompanying components
- Refactor chooseDomains.tsx into viewDomainsBase (abstract), viewDomainsView and chooseDomains
- Adds DomainName type for safety
- Adds many icon SVGs (icons not finalized yet)
- Orb tap interaction on Home Screen
- Improvements to Domains flow and update some copy to 'Life Areas'
- Add strategies to domain details view
- Tap on domains icon to see label with name

## Requirements
run `setup.bash`
change the branch of the persona repo to `qol-history-persona` ([link](https://github.com/bipolarbridges/maslo-persona/tree/qol-history-persona))

## PR Dependencies

https://github.com/bipolarbridges/maslo-persona/pull/3

## Subtasks / Progress
- [x] Add Qol history
- [x] Tap on orb on home screen
- [ ] Add all icon svgs (icons not finalized yet)
- [x] match highlighted icon to selected domains

## Preview
https://www.notion.so/polarus/QoL-History-4084812e66144c319549754ea8c9b6cf#47cc965ff92843f58c800256db1a2ee7

## Testing
First select some domains and strategies and **then** press the `SETUP History` button. Then go through the various qol history screens.

- [X] Manual

### CODE REVIEW

**Comment by rlnsy** [comment]
@MarkDavies0 we should update the base branch to either master or one of the pending PR branches.

**Comment by MarkDavies0** [comment]
> one of the pending PR branches.

It is based on #84

**Comment by brendeny** [comment]
Blank home screen on physical device testing iOS 15


After clicking orb and trying to select life areas there is a blank screen on physical device testing iOS 15


Error that popped up during testing. Clicking out of select life areas screen

**Comment by MarkDavies0** [comment]
@brendeny I think I fixed the icon missing taps and updated the spelling of self-esteem. As for the other ui bugs I think they are better left for the PR where the orb size will be adjusted. Can you double check the brain icon for me on android

**Review by wynnset — CHANGES_REQUESTED** [review]
Everything looks great here. I was just going to suggest we group the icon files into a folder (e.g. `/mobile/src/assets/images/app/domainIcons/money.svg`) and keep a consistent naming for them (some are called `SpiritualIcon.svg` and some are just `money.svg`). We should also try to name it so the file name matches the slug for each domain. Once done, please mark as ready to merge and assign back to me. Thanks!

**Review by wynnset — APPROVED** [review]

**Pull request merged**
