### PR TITLE
[Life Domains] View current focus domains and strategies

### PR DESCRIPTION
**Pull request by MarkDavies0**
## Changes
Adds new screens: `YourFocusDomainsView`, `PastStrategiesVIew`,  `viewDomainsView` and accompanying components
Refactor chooseDomains.tsx into `viewDomainsBase` (abstract), `viewDomainsView` and `chooseDomains`
Adds `DomainName` type for safety
Adds many icon SVGs (icons not finalized yet)
Orb tap interaction on Home Screen
Improvements to Domains flow and update some copy to 'Life Areas'
Add strategies to domain details view
Tap on domains icon to see label with name

## PR Dependencies
Depends on: #30 

## Subtasks / Progress

- [x] Tap on orb on home screen
- [ ] Add all icon svgs (icons not finalized yet)
- [x] match highlighted icon to selected domains

## Testing

- [X] Manual

### CODE REVIEW

**Comment by Mapleia** [comment]
Hey Mark! I've tried testing it on my Samsung S8, and I've got some bugs & screenshots. I've included them all in the google doc since there were a lot of small things (and the terminal logs I copy-pasted).

https://docs.google.com/document/d/1Whxt9Q7luc9oLgBjBSs63TIcBxULsn7Z6efit7pk8LU/edit?usp=sharing

**Comment by MarkDavies0** [comment]
@Mapleia should be all fixed up now, thanks for the help

**Comment by wynnset** [comment]
Please fix the merge conflicts when you get a chance @MarkDavies0

**Comment by wynnset** [comment]
Merging this in with #87 as it contains many fixes for this PR too

**Pull request closed without merging**
