### PR TITLE
[Dev] Update Expo, React-Native and other dependencies 

### PR DESCRIPTION
**Pull request by MarkDavies0**
## Changes
Updates React Native and Expo to work with iOS 13 and Xcode 13. Expo now uses Expo-Modules instead of RNUnimodules. Many sub dependencies had to be updated as well.

## Requirements
See the changes to the readme for new installation steps to run on android. Run the setup script

## Merged Branches and Other Dependencies
Merged branch(es): #121 

## Testing

- [x] Manual

### CODE REVIEW

**Comment by MarkDavies0** [comment]
@brendeny Can you test on physical android device please. Make sure to follow the additional install instructions outlined in the readme changes

**Comment by brendeny** [comment]
@MarkDavies0 I followed the install instructions in the readme (added those lines to the local.properties and downloaded the ndk in android studio) however there is an error upon building. Please see this text snippet: [https://snippi.com/s/fn82r6k](https://snippi.com/s/fn82r6k)

**Comment by MarkDavies0** [comment]
@brendeny Give it a try now

**Comment by brendeny** [comment]
> @brendeny Give it a try now

@MarkDavies0 still seeing the same error upon build

**Comment by MarkDavies0** [comment]
@brendeny Did you run the setup script again?

**Comment by brendeny** [comment]
@MarkDavies0 yes. Pulled changes, ran setup script and tried to sync gradle files

**Comment by MarkDavies0** [comment]
Need testing on android device

**Review by wynnset — APPROVED** [review]

**Comment by wynnset** [comment]
All seems to work well on iOS. Only need to test on Android

**Comment by MarkDavies0** [comment]
@wynnset Working on android

**Pull request merged**
