### PR TITLE
[Analysis Engine] Export new domain to graph db

### PR DESCRIPTION
**Pull request by Mapleia**
## Changes
Added export to data-service for domains. 

## Requirements
Requires: N/A

## PR Dependencies
Depends on: #30 

## Merged Branches and Other Dependencies
Merged branch(es): N/A
Other dependencies: N/A

## Testing
- [ ] Manual 
- [x] Automated

List of added tests:
- Export test for domains

### CODE REVIEW

**Comment by Mapleia** [comment]
This PR depends on a specific branch on data-service. Not quite sure if I should swap the branch reference in the Github Actions config.

**Comment by rlnsy** [comment]
> This PR depends on a specific branch on data-service. Not quite sure if I should swap the branch reference in the Github Actions config.

@Mapleia toggle it for now, then we'll switch it back master before this gets merged.

**Comment by wynnset** [comment]
@rlnsy / @Mapleia what is the bug here? What action is needed to finish / merge this PR?

**Comment by wynnset** [comment]
We have put data-services on hold for now to increase our development speed. We will use BigQuery for data export and analysis instead.

**Comment by wynnset** [comment]
Obsolete

**Pull request closed without merging**
