### PR TITLE
Google Fit API client. authentication 

### PR DESCRIPTION
**Pull request by crugwiro**
1. Followed the instructions here https://github.com/StasDoskalenko/react-native-google-fit/blob/HEAD/docs/INSTALLATION.md#getting-started
2. Did not pass new GoogleFitPackage(BuildConfig.APPLICATION_ID) in MainApplication.java, auto link takes care if this
    Add - to android Manifest.xml
3. https://developers.google.com/fit/android/get-started - followed this to set up OAuth client on the google console. ( having      issues with this because the OAuth client with the SHA1 and package name already exists, not sure how to add the fitness api to an existing client id)
- Once you pull the changes (googlefit.tsx, TipCard.tsx), after log in on android, you will be prompted to sign in to a google account.
ERROR

Does not resolve, getting stuck here

Screen Shot 2021-01-02 at 12 11 12 PM

### CODE REVIEW

**Comment by crugwiro** [comment]
1.	Followed the instructions here https://github.com/StasDoskalenko/react-native-google-fit/blob/HEAD/docs/INSTALLATION.md#getting-started
-	Do not pass new GoogleFitPackage(BuildConfig.APPLICATION_ID) in MainApplication.java, auto link takes care if this
2.	Add  ` <uses-permission android:name="android.permission.ACTIVITY_RECOGNITION"/> `  to android Manifest.xml
3.	On the GCP, go to OAuth consent screen, and add a test user for the authentication to work
4.	Copy useGoogleFit and Tipcard files to your local

**Comment by cara-wong** [comment]
@crugwiro Can you clarify the testing details for me? Here's what I've done so far:

1. Pulled down this branch and followed step 3 in your comment above as we talked about (the rest of the steps are already done)
2. Launched android (after syncing with gradle)
3. Tried logging in with email/password. After logging in, it prompted me to sign into my google account. After selecting the email I wanted to login with, it got stuck on the loading pop up
4. Rebuilt the app and tried logging in with google sign, same thing happened - got stuck on a loading pop up.

Am I missing something? (screenshot below for reference) Also still in the process of reviewing the changes file by file, so maybe I will find something from that.

Screen Shot 2021-01-28 at 1 14 23 PM

**Comment by crugwiro** [comment]
This branch has too many changes and merges across different PRs. It is safe to Close/delete.

**Comment by wynnset** [comment]
Closing as per @crugwiro

**Pull request closed without merging**
