### PR TITLE
Focus Domain and Strategies Selection (merged with master)

### PR DESCRIPTION
**Pull request by wynnset**
## Changes
Allow mobile users to select 1-3 focus domains and then choose up to 4 corresponding strategies.

Adds `domains` and `strategies` to firebase
Adds `focusDomains` and `chosenStrategies` to `userState` in firebase

## Requirements
Requires: must be up to date with #28.

## PR Dependencies
Depends on: #28

## Merged Branches and Other Dependencies
Merged branch(es):
Other dependencies:

## Subtasks / Progress
- [x] Implement UI
- [x] Integrate with firebase
- [x] Fix bugs
- [x] Replace 'key' icon in StrategiesDetailsView with correct icon for domain
- [x] Fix bug with strategies card checkbox becoming unchecked when navigating back to ChooseStrategiesView
- [x] Refactor? strategies card and `iconForDomain()`

## Preview
Screen Shot 2021-05-28 at 9 14 09 AM
Screen Shot 2021-05-28 at 9 16 48 AM

https://user-images.githubusercontent.com/71405899/120542141-990e4e00-c39f-11eb-9a48-8c2d35b25abf.mp4

## Testing
Manual

### CODE REVIEW

**Comment by wynnset** [comment]
@MarkDavies0 @rlnsy this PR still has merge conflicts...

**Comment by rlnsy** [comment]
@MarkDavies0 no idea - not sure where this branch was started and by whom

**Comment by MarkDavies0** [comment]
> @MarkDavies0 @rlnsy this PR still has merge conflicts... The original PR #30 also has merge conflicts. Is there a version of this PR that doesn't have merge conflicts?

I have not touched either PR yet as I thought you were fixing the conflicts of the original in this branch. If this is not the case I can go through the steps outlined and open a final PR without conflicts

**Comment by rlnsy** [comment]
@wynnset @MarkDavies0 please see #30, I think the fix worked quite well over there.

**Pull request closed without merging**
